// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf0b5iqaPcmh-wDP8IQzgQxlZ-2Ij29co',
    appId: '1:173867017246:web:b024fb587cdc86de96ba0f',
    messagingSenderId: '173867017246',
    projectId: 'farmus-7193a',
    authDomain: 'farmus-7193a.firebaseapp.com',
    storageBucket: 'farmus-7193a.appspot.com',
    measurementId: 'G-X6ED4M8TDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_94ZdTGmouAdANdzTUWxmwgtSIJxhvBU',
    appId: '1:173867017246:android:ad274d0382e2f1fe96ba0f',
    messagingSenderId: '173867017246',
    projectId: 'farmus-7193a',
    storageBucket: 'farmus-7193a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQSXh2e9cJHrCcTl05APNXoJQLRYqA_CA',
    appId: '1:173867017246:ios:d025db6b3617e33d96ba0f',
    messagingSenderId: '173867017246',
    projectId: 'farmus-7193a',
    storageBucket: 'farmus-7193a.appspot.com',
    iosBundleId: 'com.example.mojacknongAndroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQSXh2e9cJHrCcTl05APNXoJQLRYqA_CA',
    appId: '1:173867017246:ios:91ac5c3f656ab66696ba0f',
    messagingSenderId: '173867017246',
    projectId: 'farmus-7193a',
    storageBucket: 'farmus-7193a.appspot.com',
    iosBundleId: 'com.example.mojacknongAndroid.RunnerTests',
  );
}
